# kind-config.yaml
# Configuration pour créer un cluster Kubernetes local avec kind
# 1 control-plane + 2 workers (pour tester la tolérance à la panne)

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: fleetman
networking:
  # Cohérent avec 10.244.0.0/16 (Flannel/Kindnet)
  podSubnet: "10.244.0.0/16"
nodes:
  - role: control-plane
    # Mappe le NodePort 30080 de la web-app vers l'hôte (Windows)
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
  - role: worker

