apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
  namespace: fleetman
  labels:
    app: fleetman-queue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
        - name: app
          image: supinfo4kube/queue:1.1.0
          ports:
            - containerPort: 61616
              name: amqp
            - containerPort: 8161
              name: ui
          readinessProbe:
            tcpSocket:
              port: 61616
            initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  namespace: fleetman
  labels:
    app: fleetman-queue
spec:
  type: ClusterIP
  selector:
    app: fleetman-queue
  ports:
    - name: openwire
      port: 61616
      targetPort: 61616
    - name: ui
      port: 8161
      targetPort: ui

