apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trucks-ingress
  namespace: trucks
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: trucks.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: trucks-api-gateway
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trucks-web-app
                port:
                  number: 80

