apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  namespace: default
  labels:
    app: trucks-queue
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 61616
      targetPort: 61616
---
apiVersion: v1
kind: Endpoints
metadata:
  name: fleetman-queue
  namespace: default
subsets:
  - addresses:
      - ip: 10.244.1.54
    ports:
      - name: amqp
        port: 61616
