apiVersion: v1
kind: ConfigMap
metadata:
  name: trucks-webapp-nginx
  namespace: trucks
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events { worker_connections 1024; }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      keepalive_timeout  65;

      # Resolver pour la résolution DNS dynamique (IP du service DNS)
      resolver 10.96.0.10 valid=10s;

      server {
        listen 80;

        # Webapp statique
        location / {
          root   /usr/share/nginx/html;
          try_files $uri $uri/ /index.html;
        }

        # Redirection propre si l'app appelle /api sans slash
        location = /api {
          return 301 /api/;
        }

        # API: tout est proxifié vers l'API Gateway conforme au sujet
        # Utilisation d'une variable pour forcer la résolution DNS au runtime
        location /api/ {
          set $backend "http://trucks-api-gateway:8080";
          proxy_pass $backend/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
              proxy_connect_timeout 300s;
              proxy_send_timeout 300s;
              proxy_read_timeout 300s;
        }

        # Websocket updates via le gateway
        location /api/updates {
          set $backend "http://trucks-api-gateway:8080";
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_pass $backend/updates;
        }
      }
    }

